on:
  push:
    branches:
      - main

name: Production - Build and Deploy

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build Javascript
        run: |
          npm run build

      - name: Publish package to npm
        run: |
          npm ci
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}